//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFSplit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFSplit.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string AbortCaption {
            get {
                return ResourceManager.GetString("AbortCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The splitting of the file was aborted.
        /// </summary>
        internal static string AbortText {
            get {
                return ResourceManager.GetString("AbortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a PDF file.
        /// </summary>
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the unit.
        /// </summary>
        internal static string ChooseUnit {
            get {
                return ResourceManager.GetString("ChooseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DoneCaption {
            get {
                return ResourceManager.GetString("DoneCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The splitting of the file is completed.
        /// </summary>
        internal static string DoneText {
            get {
                return ResourceManager.GetString("DoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End prematurely.
        /// </summary>
        internal static string EndPrematurely {
            get {
                return ResourceManager.GetString("EndPrematurely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an integer.
        /// </summary>
        internal static string EnterInteger {
            get {
                return ResourceManager.GetString("EnterInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string FileNotFoundCaption {
            get {
                return ResourceManager.GetString("FileNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file could not be found.
        /// </summary>
        internal static string FileNotFoundText {
            get {
                return ResourceManager.GetString("FileNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PDF file.
        /// </summary>
        internal static string FileNotPdfCaption {
            get {
                return ResourceManager.GetString("FileNotPdfCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file is not a PDF file.
        /// </summary>
        internal static string FileNotPdfText {
            get {
                return ResourceManager.GetString("FileNotPdfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File small enough.
        /// </summary>
        internal static string FileSmallEnoughCaption {
            get {
                return ResourceManager.GetString("FileSmallEnoughCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file is already small enough.
        /// </summary>
        internal static string FileSmallEnoughText {
            get {
                return ResourceManager.GetString("FileSmallEnoughText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integer must be greater than 0.
        /// </summary>
        internal static string IntegerGreaterZero {
            get {
                return ResourceManager.GetString("IntegerGreaterZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit is invalid.
        /// </summary>
        internal static string InvalidUnit {
            get {
                return ResourceManager.GetString("InvalidUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiB.
        /// </summary>
        internal static string MiB {
            get {
                return ResourceManager.GetString("MiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF-Files.
        /// </summary>
        internal static string PdfFiles {
            get {
                return ResourceManager.GetString("PdfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Splitting.
        /// </summary>
        internal static string StartSplitting {
            get {
                return ResourceManager.GetString("StartSplitting", resourceCulture);
            }
        }
    }
}
